#+TITLE: ★列宁在1918：革命の功利主义

** 按 

这是一篇写于 2015 年 10 月前后的旧文了，集中表达了我对人生观的一些个性化的观点。为了避免不必要的误解，应当首先申明本文中的“功利主义”一词完全是在不带褒贬的中性意义上使用的，既不同于西方哲学中的功利主义，也不同于我们日常生活中流行的“利己主义或个人主义”。我使用这个词，只是想在承认既存社会状况普遍制约的前提下同时强调保持一种积极进取的人生态度和生活态度的重要性，我们不应该逃避斗争（不论这些斗争是社会的阶级斗争，还是生活斗争、学习斗争）相反应当以高度热情和革命的使命感而投入到这些斗争中去，并力争夺取在这些领域斗争的胜利。哪怕这些斗争有时候由于时代的必然的制约性而表现为某种“人生的功利主义战场”的色彩，仿佛只表现为“对自己个人和家庭有利”，但是，我们可以也应该去努力争取这种个人的发展，并在同样程度上把这些“发展和利益”转化为整个无产阶级事业的发展和利益。

正如毛在《在延安文艺座谈会上的讲话》里说的那样：“我们的这种态度是不是功利主义的？唯物主义者并不一般地反对功利主义……世界上没有什么超功利主义，在阶级社会里，不是这一阶级的功利主义，就是那一阶级的功利主义。我们是无产阶级的革命的功利主义者，我们是以占全人口百分之九十以上的最广大群众的目前利益和将来利益的统一为出发点的，所以我们是以最广和最远为目标的革命的功利主义者，而不是只看到局部和目前的狭隘的功利主义者。”

每个人的人生观也不尽相同，我已经考虑到了文章内容所可能引发的一些误解和疑惑，但这并不妨碍它的参考价值。

革命の功利主义，此乃我的人生定位。它凝结了这个时代真正有所追求之人的全部要义，其乃吾辈人生实现之最高定义与价值追求，它为本人之一切行动皆围绕展开和延伸的核心之所在。

一定的主义，所谓一定的人生准则和价值追求，不外是特定历史时代里具体、历史的个人活动的展开中赖以实现自我的方式、途径。伴随着时代的更替，历史活动内容的变更，必然是活动展开方式的更替，因而也就是人的自我实现方式之更替。每个历史时代都有着区别于其他时代的特殊内在规定性，因而在这些特殊时代条件下，必然是人之自我实现方式的特殊规定。如果能较好把握这一点主动去适应该时代之规定性而去谋求人生实现，即能较大可能取得为阶级社会公认价值所认可的那种被称为“成功”的效果；反之，若与时代规定性对抗，由于与时代大环境的相斥性，则不免取得被阶级社会称之为“失败”的那种后果。

** 资本的时代规定性

因此要正确实现人生定位，首先得搞清楚被我们称之为 21 世纪的这个世界，和被称之为中国的这个国度，它们时代规定性究竟为何，因为二者皆为吾辈此生活动赖以展开和价值赖以实现的舞台与背景；只有解决了该问题，才能把握本质，较好地规划人生。被称为唯物主义者的人，应该是那种最能随机应变、善于从事物既存规律出发把握本质，从而利用一切有利条件为实现革命的目的而服务的人。

《共产党宣言》毫不掩饰地道破了一个事实——自从有文字开始的人类历史，不外是一幅交织着各阶级为了利益而相互斗争、角逐的历史。我们只需稍微对现实做一个考察，那么很容易看出，我们现在所处的世界、所处的国度依然未能超越历史唯物主义阶级社会视野的范畴，依然是阶级对抗中前进的世界；我们所既存的时代，依然是整套资本主义生产方式占据主导的时代，同时因而也是与该历史阶段生产方式相适应的意识形态和价值观念占据主导的时代。或者以马克思“社会形态三阶段”的划分，我们尚处于人类历史第一阶段（人的依赖关系，是最初的社会形态，在这种形态下，人的生产能力只是在狭窄的范围内和孤立的地点上发展着。）与第三阶段（建立在个人全面发展和他们共同的社会生产能力成为他们的社会财富这一基础上的自由个性）之间的第二历史阶段（以物的依赖性为基础的人的独立性，是第二大社会形态，在这种形态下，才形成普遍的社会物质交换、全面的关系、多方面的需求以及全面的能力体系）。资本主义社会属于第二阶段，社会主义与共产主义属于第三阶段。我们远远没有进入第三阶段。

这个时代普遍地是属于资本主义的，与此相适应，普遍的市民价值观是功利主义（或称利己主义）的——这个时代的人还不得不被分化为一个个屈服于物的力量下的相对独立的群体，利己主义与拜金主义成为他们的全部“成功”要义，货币和商品取得了自己虚幻的外表，人们日以继夜消费着拜物教的光环，同时消费着自己无聊乏味的生命。金钱成为这个时代一切活动赖以旋转的轴心，它迫使每一个时代人做出抉择——要么服从资本的逻辑接受支配，要么滚出资本的社会堕入深渊。如果有 10% 的利润，资本就会保证到处被使用；有 20% 的利润，资本就能活跃起来；有 50% 的利润，资本就会铤而走险；为了 100% 的利润，资本就敢践踏一切人间法律；有 300% 以上的利润，资本就敢犯任何罪行，甚至去冒绞首的危险。资本不是一种个人力量，而是一种社会的力量；资本犹如千万条无处不在的锁链，将每个个人牢牢锁住。一百多年来，资本主义从未改变其追逐利润而漠视人的本质。

时代并没有超越第二历史阶段，那么中国呢？中国已经超越第二阶段进入到每个人全面而自由发展的第三阶段了吗？很明显，我所在的国度——中华人民共和国也未能幸免。有人说，第一，中国是社会主义社会，社会主义社会不存在阶级对抗；第二，市场经济只是单纯一种资源配置方式如此等等。可惜，这些令人乏味的自欺欺人来源于对历史发展的无知。

针对第一个问题，严格意义上，历史上未曾有一个国家曾进入过社会主义社会（即历史第三阶段，自由而全面发展），包括苏联东欧、中国等国现实建立起来的社会主义制度，只能被称为“现实社会主义”，而这种“现实社会主义”与马克思主义中所论述的被称之为“经典社会主义”的科学社会主义直接实践的制度，实际是存在着各自赖以建立的巨大内在物质基础差距的。它们只能被称为后发展国家的社会主义，是在经济文化落后、生产社会化的历史任务尚未完成的背景下建立起来的一种不够格的社会主义，而并非是科学社会主义的直接实践，怎么能够被视为进入了社会主义社会呢？如果我们已经处在社会主义了，那么这个国家还是这样一个令人失望的模样吗？中国依然有一大批尚未搞清这个问题的人们在做着梦。

针对第二个问题，市场真的只是一种资源配置方式这么简单吗？这是庸俗经济学家以交换方式取代生产方式后的一厢情愿。市场经济体现的是一整套的资本的生产方式，其是人类历史第二阶段的专属物。第一，商品生产的存在必须有两个一般条件：一是社会分工，生产者之间存在相互依赖的关系，因而存在交换产品的要求；二是产品属于不同的所有者，生产者之间必须按照耗费的社会必要劳动实行等价交换。因此，真正的商品生产和商品交换不存在于共同体内部；一旦共同体内部不同机构之间出现了商品交换，共同体本身就变得松散和面临解体了。第二，商品生产在其发展过程中经历了性质不同的两个阶段，即简单商品生产和资本主义商品生产。资本主义商品生产是普遍化的商品生产，劳动力也成为商品，一切有使用价值的典型都趋向商品化。市场经济不是和商品生产等同的概念。市场经济作为由市场机制配置资源的经济形式，不同于简单商品生产，而是普遍化的商品生产，是商品生产的高级阶段和现代形态。在这个阶段，虽然仍然会存在一定的简单商品生产，但作为主体的形式不再是简单商品生产。市场经济的存在除了上述两个一般条件之外，还必须有特殊条件。首先，生产的直接目的不是使用价值（既不是直接的使用价值，也不是间接的使用价值，即不是通过商品交换取得使用价值），而是使现有的价值增值，即获得剩余价值。这就意味着，生产条件是作为资本来使用的。其次，生产要素必须能够在全社会范围内自由流动和配置。这就意味着劳动和所有权必须分离，劳动者本身必须作为商品进入市场，劳动必须采取雇佣劳动的形式。概括地说，市场经济的存在还必须具有第三个条件，就是资本主义生产方式必须成为主体。就这个意义来说，市场经济基本上是资本主义经济。

因此，改革开放后的中国不过是资本主义生产方式占据了主导地位的中国，雇佣劳动的普遍化，剥削与私有制的再生，通过改革，中国社会重塑了一整个的新生资产阶级。因此，中国社会依然属于人类社会发展的第二阶段——以物的依赖性为基础的人的独立性。在中国与该历史阶段相适应的价值体系与实现方式，也只能是功利主义的。在第二阶段，自然只能做第二阶段的事。

当我们观察周围，会发现一百多年前《共产党宣言》的那些精辟论述依然是现存社会的生动写照：“资产阶级在它已经取得了统治的地方把一切封建的、宗法的和田园般的关系都破坏了。它无情地斩断了把人们束缚于天然尊长的形形色色的封建羁绊，它使人和人之间除了赤裸裸的利害关系，除了冷酷无情的“现金交易”，就再也没有任何别的联系了。它把宗教虔诚、骑士热忱、小市民伤感这些情感的神圣发作，淹没在利己主义打算的冰水之中。它把人的尊严变成了交换价值，用一种没有良心的贸易自由代替了无数特许的和自力挣得的自由。总而言之，它用公开的、无耻的、直接的、露骨的剥削代替了由宗教幻想和政治幻想掩盖着的剥削。资产阶级抹去了一切向来受人尊崇和令人敬畏的职业的神圣光环。它把医生、律师、教士、诗人和学者变成了它出钱招雇的雇佣劳动者。 ”历来在教科书与社会主义国家传统马克思主义视域里对资本主义所批判得一切丑恶现象，正在中国现实大地上得到十足的上演，共和国的光彩因它们而黯淡，国旗与党旗的鲜红因它们而褪色不少，但这不过是资本主义带来的必然结果——至今究竟还有多少人天真地把中国社会既存问题与资本主义的对立物马克思主义、社会主义制度捆绑起来大加批判呢？这些问题是资本主义历史阶段的必然，是自由主义改革和建立市场经济体制的必然，改革开放的过程其实是不再与科学社会主义对号入座的过程，这些问题的暴露其实与科学社会主义半点关系都没有。

特定的资本时代规定性下，与之相适应的是特定的人之实现方式。正如在封建时代人的自我实现只能以宗法、血缘和等级的内容作为凭借，在资本占据统治地位的时代，人的自我实现则只能以功利（利己）、金钱本位的内容作为凭借。时代如此，在中国莫能例外。一切以个体利益最大化为一切活动追求的功利主义作为终极目标，这就是现存社会的运动实质，一个资本支配下的市侩社会的实质。这一规律性正在无时不刻不被我们身处的周围无数具体直观可感的经验和事例所反复证实着。

** 资本时代规定下的革命者——革命の功利主义者

资本时代规定下的社会只能是一个市侩社会而绝不会是“社会主义法治”社会；这只能是一个到处充斥着纯粹金钱关系的利己主义的社会，而绝不会是一个“人人为我，我为人人”的社会主义社会。

这是资本主义时代的悲哀。在这个时代，财富的新源泉，由于某种奇怪的、不可思议的魔力而变成贫困的源泉。技术的胜利与生产力的进步，似乎是以道德的败坏为代价换来的。随着人类愈益控制自然，生产越是发展，个人却似乎愈益成为别人的奴隶或自身的卑劣行为的奴隶。我们的一切发现和进步，似乎结果是使物质力量成为有智慧的生命，而人的生命则化为愚钝的物质力量。资本主义时代中与资本积累相对应的是另一头的贫困积累，在一极是财富的积累同时在另一极，即把自己的产品作为资本来生产的阶级方面，是贫困、劳动折磨、受奴役、无知、粗野和道德堕落的积累。这个时代迫使每个人都服从既定的资本增长逻辑而变为功利主义者。

这个时代使野蛮时代每一以简单方式犯下的罪恶，都采取了复杂的、暧昧的、两面的、虚伪的存在形式。

在资本主义经济的生产时代中，人的内在本质的这种充分发挥，表现为完全的空虚化；这种普遍的对象化过程，表现为全面的异化，而一切既定的片面目的的废弃，则表现为为了某种纯粹外在的目的而牺牲自己的目的本身。市侩和庸人们在这一时代规定性之下沦丧，他们唯一所能做的不过是顺从、麻木不仁和日趋神经衰弱，成年累月为获取微薄的生存资料而不断出卖自己的劳动力，接受剥削与压榨，成为一个资本战车的忠实奴仆，在这个不幸的时代中浑浑噩噩度过一生；他们的全部活动不过围绕“利己”二字展开，当然在家庭关系笼罩下还表现为“利家”，最多也只是“利家”，超越此范围的并不在考察范围内；他们是真正的贫乏者，价值符号和货币富足掩饰不了其被异化的悲剧性命运。他们没有思想，不会独立思考，因为早已有资本集团控制的文化工业按量和按其需求以流水线方式生产出一批批低劣得文化消费品供其享用，塑造他们的需求和价值观；固定的社会分工使他们成为才能上的残废，职业的痴呆为资本主义生产所需要，他们一生几乎如一部巨大机器上的螺丝钉一般固定于某一社会分工上，决不能超出其谋生领域的需要、利己的需要来实现自我。

资本的时代规定性已经腐蚀了一切，历史为我们中国人做了一个绝佳的嘲讽——革命先烈们抛头颅洒热血所换来的人民共和国，现在正在对自己的革命史与革命英雄人物进行着解构与嘲讽；劳动与赤诚不再被人们所赞颂，而不过是愚蠢和无能的代名词；雷锋死了，在现存人们的记忆中，他只是来源于过去遥远时代某种完美人格的化身，这个功利主义的时代，再也没有雷锋成长的土壤。利己主义与个人主义正在中国的大地上复苏，抵御功利主义的堡垒的党也遭到严重腐蚀。过去为我们先辈所批判的一切，今天再次死灰重燃了，并且取得了实际上冠之以“主流”的社会支配地位。无论“党员”们的政治面貌在人事表格上如何填写，从实质的意义上说，无论是他们的追求还是他们的行为都并不是属于共产党的，他们的一切同党性也没有任何联系。他们既不是国民党、也不是美国间谍，他们只是中国人，仅仅只是一个在中国这片土地上，被悠久历史和当下时代中的新事物所相互缠绕起来的条件所造成的人。但这所造成的，最能令人感到悲痛的事情只有一件，五星仍然在他们的头上闪烁着。我不止一次地悲叹：庸人和市侩盘踞着你的机关，而忠诚的人徘徊在外受其欺凌，他们从热情到冷淡，从笑容到泪水，从希望到失望，从簇拥到离开……

当然，这种利己主义的实现方式在当下具有充分的历史正当性，趋利避害、谋求利益最大化是人之活动的预设机制，当利益最大化只能以利己和功利而不是以同时利他为前提的时代，功利主义就成为了无疑的实现选择。衣食住行是维持生命的基本前提，而有生命的个人的存在，无疑是人类历史的第一个前提；在衣食住行要靠功利主义来取得的时代，功利主义即为人的实现方式。

以上所述，也正是这个时代绝大多数人的生存状况。
单纯只是通过功利主义来谋求生存，来实现自我，以此作为人生目的和愉悦所在，是堕入大多数人即庸人的行列。并不是所有人都是浑浑噩噩度过一生，资本规定下的时代也存在能够超越资本逻辑而行事的那部分人，这部分人并没有在资本编织的迷梦中丧失自我，他们致力于反抗和最终埋葬这个资本规定性时代的真正努力——共产主义运动，重新将之视为人生的目的和意义。他们从先辈手里接过鲜艳的战斗的旗帜，以严密完整而彻底的革命理论——马克思主义武装自己的头脑。他们深知，资本规定性的时代并不是某种永世长存的神话，马克思主义揭示了：资本的逻辑并非永存，资本主义时代正如其曾经取而代之的那个封建时代一样，并不是一个坚实不变的实体，它的自我内部运动规律必然有使其崩溃并为更高级社会形态，为人类历史第三阶段开辟道路的一天。舍此就不能完成人本质的自我占有和复归。这部分人，就是资本主义时代的革命者，资本主义时代的战斗的马克思主义者。

被我们所称之为资本的时代规定下的革命者们，就是这样一种人——

他们对该历史趋势有着高度灵敏的觉察力和自觉性， 他们能以超越功利主义的逻辑去从事另一项不同凡响的事业：他们明白，他们的幸福最终将属于千百万人，他们的事业不必显赫一时，但会默默地并永远发挥作用地存在下去——这项事业致力于人类解放，揭露这个资本规定性的时代的运动铁律，迎接其崩溃而为更高社会形态替代的一天；

他们绝不如庸人一般把作为谋生工具的功利主义、追求个体经济利益最大化作为人生目的或愉悦的源泉本身，他们献身于另一壮丽的事业：他们明白，功利主义只是在该历史阶段下的人生价值之必然实现方式，但方式决不能成为目的，其作为工具应该服务于革命的目的——这一目的才是他们人生价值之真正所在与实现；

他们将以高度的热情和精力投入到人生的功利主义战场之中，谋求利益的最大化，在现时代无情生存斗争中取得功利主义竞争的胜利，但是绝不以此止步：他们将利用既得的最大利益成果再以更加高度的热情和赤诚投入到革命事业。他们明白，唯有利用一切可供利用之条件，调动一切积极因素，才能促成真正人生价值之实现，革命目标的实现；

他们是资本规定性时代下的功利主义者，而且将以最顽强的姿态战斗在功利的战场，无情地夺取每一次的胜利，但他们与同时代人的根本区别又在于：他们所做的一切，服从于革命的最高目的，他们不为功利而功利。奉行功利主义的价值准则不过是他们在争取更加有利的斗争条件，为献身革命的事业而铺垫道路。功利主义是革命的功利主义。

而这项革命的事业，就是共产主义的事业，是在后发展国家社会主义建设过程中保卫既存的社会主义因素、从理论与实践上推进中国社会主义的历史性事业；就是讨论、传播与捍卫共产主义的原则，继承与运用、发展马克思主义的事业；就是深化对后发展国家建设社会主义的基本规律的认识、并利用这一规律保证我国未来科学社会主义基本前途的事业；就是对当代各种非科学社会主义进行批驳和揭露、捍卫科学社会主义在中国的地位的事业。他们知道个人的力量微不足道，可是他们也知道，团结就是力量。（这项事业，同时也是将自己同整个中国无产阶级的命运和利益紧密联系起来、以各种方式参与到为了工人阶级和劳动解放而进行的斗争中来；把自己微薄的力量和掌握的资源尽可能地献于这项历史性的事业，是革命前缀的必然要求。——作者补）

在无产阶级的革命导师恩格斯身上，革命与功利主义二者得到了完美结合。恩格斯是经营着曼彻斯特工厂的天才的企业家和实干家；正是这种功利主义成为其接济马克思、投资于革命活动的物质来源。他所抱怨的“鬼商业”并没有磨灭他的志向与追求，相反，资本主义的企业主这只是他的一个侧面，他同时是一个坚定的革命者，以顽强毅力和高度热情投入到国际共产主义运动中去。他是功利主义者，但他更是一个革命者。瞧，这就是资本规定性时代下的功利主义者，功利主义之前的革命之定语限制，是他们区别于其他人的关键性所在，也是他们得以超越一般人的实质所在。从这个意义上，革命的目的与事业，就是他们生命组成之一部分，失去了这一定语，这一组成，他们就不再成其为他们。

前进吧，革命の功利主义者们，为了革命的事业，为了中国社会主义的未来！我们献身于这壮丽的事业，无上幸福，无上荣光！

**  后记

在和一些朋友们交流的过程中，经常听见他们这样的疑惑：既然中国教育制度只是应试的和功利的，那么还要不要去努力考高分?大学毕业后考上了一个机关职员，是不是该放弃这个机会以免“脱离群众”?以后选择工作时是不是应当拒绝任何“可能腐蚀意志的较高收入和环境较好”的职业?

对这些问题的回答其实已经多少包含在这篇文章中了。就现阶段而言，通牒式的让人人都下工厂搞工运那是不现实的，而且那未必就是马克思主义。社会主义必然赖于无产阶级的组织和行动，我们也应当努力去靠近和融入无产阶级，成为中间有机的一份子。但斗争方式是多样的，而一些限于各种条件，我们中的一些人可能暂时没有直接斗争的机会，不必因此焦虑或自愧，他们完全可以继续保持阶级同路人的状态，保持对阶级话题的关注和以一定程度的自我牺牲（时间精力和金钱）参与到社会主义事业中来。
