#+TITLE: 对问题“马克思无差别的人类劳动，与平均主义、大锅饭有什么区别？”的回答

答：他们的区别大的很，就像巴基斯坦和卡巴斯基一样。

** 无差别人类劳动

我们先看[[http://marxists.anu.edu.au/chinese/marx/capital/03.htm][《资本论》]]原著：

#+BEGIN_QUOTE
商品在它的价值形态上蜕掉了它自然形成的使用价值的一切痕迹，蜕掉了创造它的那种特殊有用劳动的一切痕迹，蛹化为无差别的人类劳动的同样的社会化身。
#+END_QUOTE

这就是马克思所指的 *“无差别人类劳动”* ，这里怎么理解？

我们再看[[http://marxists.anu.edu.au/chinese/dictionary-of-marxism/marxist.org-chinese-dictionary-of-marxism-V.htm#1][二手资料]]的解释：

#+BEGIN_QUOTE
在交换过程中，表示同质的某种东西，并且所有商品都具有唯一的共同属性，就是它们都是劳动产品。交换过程使生产商品的的所有不同类型的劳动在质上相同，生产商品的这种同质劳动叫做抽象劳动。价值就是抽象劳动的对象化或物化，价值的表现形式就是商品的交换价值。
#+END_QUOTE

这说明商品中所凝固的抽象人类劳动是无差别的。无差别人类劳动是资本主义社会关系所采取的特殊形式——价值形式的表现。这个概念的提出，实际上掀开商品的技术面纱，反映了资本主义下人压迫人的社会关系。

** 平均主义、大锅饭

平均主义、大锅饭属于分配领域，它是一种分配关系。这个故事我们又得另说了。

首先我们来说“大锅饭”。“大锅饭”这个词的提出表达了资产阶级对于人民公社限制资产阶级法权的分配关系的批评，他们认为“社员无论干多干少，干好干坏，都不会影响个人工资分配”，但实际上人民公社也是反对这种极端平均主义的：

#+BEGIN_QUOTE
实行“各尽所能，按劳分配”的原则，承认不同劳动者在劳动上的差别，就会在劳动报酬上保持一定的差别。这
在社会主义历史阶段是不可避免的。而绝对平均主义却要求个人消费品的分配必须平均、划一，不问劳动的数量和质量，不问对国家贡献的大小，不问工作需要，一律付给平均的报酬，只有这样才算平等。这种绝对平均主义是小资产阶级的虚伪的平等观在分配问题上的表现，是手工业和小农经济的产物，同社会主义和共产主义毫无共同之处。毛主席指出:“绝对平均主义不但在资本主义没有消灭的时期，只是农民小资产者的一种幻想；就是在社会主义时期，物质的分配也要按照‘各尽所能按劳取酬’的原则和工作的需要，决无所谓绝对的平均”。因此，实行“各尽所能，按劳分配”的原则，要反对绝对平均主义。[fn:1]
#+END_QUOTE

资产阶级攻击的，不是平均主义，而是人民公社反对在劳动报酬上扩大差别的做法。

那么，人民公社为什么要反对在工资上扩大差别呢？

#+BEGIN_QUOTE
社会主义社会还不是完全成熟的共产主义，同完全成熟了的共产主义社会相比，又有着质的差别。正如马克思所
说的，社会主义社会“在各方面，在经济、道德和精神方面都还带着它脱胎出来的那个旧社会的痕迹”。[fn:2]
#+END_QUOTE

社会主义制度仍然保留商品生产、按劳分配、资产阶级法权，这一点跟资本主义没有什么差别。总之，社会主义仍然存在阶级斗争，存在着资本主义复辟的危险性。

无产阶级要想实现共产主义，就必须不断地解决生产关系和生产力、上层建筑和经济基础之间的矛盾，发展共产主义因素，清除资本主义痕迹。从社会主义到共产主义，必须经历深刻的社会革命。

* Footnotes

[fn:2] 同上
[fn:1] 《政治经济学讲话（社会主义部分）》
