#+TITLE: 【尊马讨修 №2】他们为什么要自欺欺人？

修正主义者一向极端痛恨社会主义革命，自从苏中两国资产阶级复辟后，他们便靠吃诋毁苏中社会主义建设的伟大成就、诋毁伟大旗手斯大林同志、伟大舵手毛主席和拥护他们的伟大人民这碗饭为生。他们越是使劲辱骂社会主义国家，越是能够讨得你国资产阶级及其拥护者粉红小将的欢心，越是能够赢得各路牛鬼蛇神反对派的赞誉，他们就跟享用更多中修帝国主义的残羹冷炙，中修帝国主义的慷慨施舍还能为修正小丑们继续恶毒地攻击世界共产主义运动增添了动力。修正主义者跪添资本主义的丑陋嘴脸已为所有的革命马克思主义者、觉悟的无产阶级所不齿，而修正小丑们不以此为耻，反以此为荣，继续撒播一个又一个颠倒历史黑白的弥天大谎，真是无耻到了极点，可惜，谎言遮盖不了真相，反而暴露出修正主义叛徒集团极度虚弱、极度害怕马列主义的革命真理、极度不愿意面对历史真相的丑陋面目，而澄清修正叛徒集团们散布的弥天大谎，对于今日马克思主义具有重大的意义。

最近，一些国家主义者、民族主义者又蹦达出来舒活舒活筋骨，抖擞抖擞精神了。他们为了疯狂攻击马克思主义，又从历史垃圾堆里翻出这些破烂，尽管这些谎言谬论又肮脏又无耻又不值一驳，却不妨碍这些资产阶级的孝子贤孙捡起这些不值一驳的谣言谬论抹黑马克思主义，妄图掀起新一轮的反共高潮，便于他推销已成历史垃圾的谬论。

* 谬论一：主体性的“神话” 

这些修正主义者说什么无产阶级素质底下、现存的工人阶级力量有限、无法夺取政权只能被外国利用、只能放弃革命，令人啼笑皆非，修正叛徒一向喜把欢劳动人民绑在他们的修正主义战车上，可惜他们的阴险图谋却一次次地破产，一次次地失败。无产阶级革命是否能够成功，是看有没有一个先锋队。在整个无产阶级中，先进分子当然是少数。在群众运动中，少数先进的人需要带领大多数不先进的人前进，后者需要前者的领导才能走在正确的道路上。如果工人阶级个个精通马列主义，那要先锋队干嘛？还有，工人阶级的力量不是由“工人阶级在全国人口中所占的比例”决定的，这是所谓的“唯生产力”论。

而这些修正主义的孝子贤孙还把群众与先锋队对立起来：胡说什么先锋队只能产生于产业工人群体，不能产生于“革命知识分子”。出身不由己，道路自选择。阶级出身这玩意是打烙印的，成长的家庭环境对人的影响是客观存在的，在这一点上不应采取鸵鸟政策。当然，选择走什么路归根结底是自己决定的。能做的，只能是坚持“有成分论不唯成分论”、“重在表现”、“出身不由己、道路可选择”的原则。内因起决定作用，外因通过内因起作用。我们承认内因的决定作用，但不能因此否认外因的作用。血统论和出身论，都是形而上学的谬论，前者倒向外因论，后者则割裂外因和内因，否认外因的作用。 

无产阶级先锋队的先进性来自于它的组织性、纪律性、革命性。最有纪律的劳动者来自于流水线，但脑力劳动者就没有这种组织性、纪律性吗？现在的码农、画师的工作不就已经流水线化了吗？革命性从哪里来？——群体斗争情绪、斗争经验和自觉性。

* 谬论二：“融工”派

够了！够了！这些修正主义为了葬送革命，居然打出“融工”的口号：胡说什么只有“融工”的左青才是左青，帮助工人维权、组织 NGO 的、给工人提供法律咨询的左青都是“伪左青”，真是笑死我了。这种盲动的的路线，无非只是要鲁迅拿枪弃笔罢了。没有一定基础的左青盲目融工只能有一下两种结果：

1. 被资产阶级洗脑，认为工人都直男癌、醺酒、嗜赌，只注意到工人阶级中的落后分子，丧失革命热情；
2. 缺乏斗争艺术，无法与工友合作，被资产阶级发现并驱逐。

参与无产阶级的斗争，不是非得只有“融工”一条路可以走。再说，你进厂也不一定能够参加流水线生产，而且天朝现在的无产阶级还不是一个“自为”的阶级，你以为现在还是文革时期啊？现在的天朝乃是资本主义社会，这样一个自在的阶级能够教会新人什么革命性呢？

世界上没有自来红，只有改造红；没有“来自灵魂深处”的革命，只有先锋队领导的革命。进厂做工算是一个办法，但这个办法本身绝不是灵丹妙药！
